services:
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=roo
      - MYSQL_USER=admin
    ports:
      - '3306:3306'
