spring:
  application:
    name: 'demo springboot '
  liquibase:
    url: jdbc:mysql://localhost:3306/dev
    enabled: false
    user: 'admin'
    password: 'admin'
    change-log: db/changelog/changelog-master.xml
  datasource:
    hikari:
      maximum-pool-size: 20
      max-lifetime: 5000
      jdbc-url: jdbc:mysql://localhost:3306/dev
      username: 'admin'
      password: 'admin'
  jpa:
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
server:
  port: 8080